# CSV INE

El análisis de datos de turismo es una herramienta poderosa para comprender mejor el comportamiento de los viajeros y su impacto en las regiones. Para este proyecto, he seleccionado el conjunto de datos "Viajeros y Pernoctaciones por Comunidades Autónomas y Provincias" proporcionado por el Instituto Nacional de Estadística (INE). La elección se basa en la importancia del turismo en la economía española y la riqueza de información que este conjunto de datos ofrece. A través de este análisis, busco desvelar patrones y tendencias que ayuden a comprender y mejorar la gestión del turismo en nuestras regiones. ¡Comencemos este viaje de descubrimiento!

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
%run functions.ipynb
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)

In [2]:
ruta_archivo= '../data/INE.csv'

En el jupyter notebook de 'functions.ipynb' he aplicado funciones para limpiar y ordenar estos datos por cada año:

## 2022

In [46]:
ine22= leer_archivo_rango_periodo(ruta_archivo, '2022')
ine22.head()

,ï»¿Totales Territoriales,Comunidades y Ciudades AutÃ³nomas,Provincias,Viajeros y pernoctaciones,Residencia: Nivel 1,Residencia: Nivel 2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M12,6.054.556
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M11,6.284.698
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M10,9.743.259
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M09,11.050.305
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M08,12.889.916

In [4]:
ine22_viajeros, ine22_pernoctaciones = procesar_ine_data(ine22)

In [5]:
ine22_viajeros.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M12,6.054.556
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M11,6.284.698
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M10,9.743.259
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M09,11.050.305
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2022M08,12.889.916

In [6]:
ine22_pernoctaciones.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2022M12,16.627.833
1,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2022M11,17.661.676
2,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2022M10,29.865.924
3,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2022M09,35.999.861
4,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2022M08,46.140.100

### VIAJEROS

In [7]:
viajeros22 = procesar_viajeros(ine22_viajeros)
viajeros22.head()

,2022M01_Residentes en Espana,2022M01_Residentes en el Extranjero,2022M02_Residentes en Espana,2022M02_Residentes en el Extranjero,2022M03_Residentes en Espana,2022M03_Residentes en el Extranjero,2022M04_Residentes en Espana,2022M04_Residentes en el Extranjero,2022M05_Residentes en Espana,2022M05_Residentes en el Extranjero,2022M06_Residentes en Espana,2022M06_Residentes en el Extranjero,2022M07_Residentes en Espana,2022M07_Residentes en el Extranjero,2022M08_Residentes en Espana,2022M08_Residentes en el Extranjero,2022M09_Residentes en Espana,2022M09_Residentes en el Extranjero,2022M10_Residentes en Espana,2022M10_Residentes en el Extranjero,2022M11_Residentes en Espana,2022M11_Residentes en el Extranjero,2022M12_Residentes en Espana,2022M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,51.283,10.804,72.223,13.320,82.649,24.794,119.875,57.536,119.893,97.410,132.289,94.573,194.874,82.142,232.843,80.681,150.900,105.761,131.666,94.199,94.029,28.034,79.982,18.050
ALBACETE,15.963,1.525,20.754,2.755,25.686,2.440,33.808,3.040,31.837,3.871,31.137,3.350,29.234,3.624,33.219,4.218,34.265,3.715,32.825,3.847,26.850,3.848,23.932,2.356
ALICANTE,75.778,49.765,133.494,78.422,135.526,124.360,221.231,168.677,209.441,196.679,253.485,195.961,319.351,217.146,341.418,219.568,209.071,210.661,186.149,187.378,169.490,123.020,163.532,97.349
ALMERIA,22.290,9.007,39.146,10.284,42.511,13.274,70.416,19.025,90.422,28.431,153.172,32.084,189.343,39.566,206.936,41.392,142.904,34.974,71.229,26.150,38.622,12.693,33.013,10.226
ARABA/ALAVA,14.076,4.006,18.289,4.280,23.209,6.003,26.586,8.969,25.469,11.329,24.420,13.411,28.057,20.638,31.811,20.632,26.529,14.493,28.037,10.666,24.043,6.280,24.316,5.299

In [8]:
#Exporto el csv
viajeros22.to_csv('viajeros22.csv')

### PERNOCTACIONES

In [9]:
pernoctaciones22 = procesar_viajeros(ine22_viajeros)
pernoctaciones22.head()

,2022M01_Residentes en Espana,2022M01_Residentes en el Extranjero,2022M02_Residentes en Espana,2022M02_Residentes en el Extranjero,2022M03_Residentes en Espana,2022M03_Residentes en el Extranjero,2022M04_Residentes en Espana,2022M04_Residentes en el Extranjero,2022M05_Residentes en Espana,2022M05_Residentes en el Extranjero,2022M06_Residentes en Espana,2022M06_Residentes en el Extranjero,2022M07_Residentes en Espana,2022M07_Residentes en el Extranjero,2022M08_Residentes en Espana,2022M08_Residentes en el Extranjero,2022M09_Residentes en Espana,2022M09_Residentes en el Extranjero,2022M10_Residentes en Espana,2022M10_Residentes en el Extranjero,2022M11_Residentes en Espana,2022M11_Residentes en el Extranjero,2022M12_Residentes en Espana,2022M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,51.283,10.804,72.223,13.320,82.649,24.794,119.875,57.536,119.893,97.410,132.289,94.573,194.874,82.142,232.843,80.681,150.900,105.761,131.666,94.199,94.029,28.034,79.982,18.050
ALBACETE,15.963,1.525,20.754,2.755,25.686,2.440,33.808,3.040,31.837,3.871,31.137,3.350,29.234,3.624,33.219,4.218,34.265,3.715,32.825,3.847,26.850,3.848,23.932,2.356
ALICANTE,75.778,49.765,133.494,78.422,135.526,124.360,221.231,168.677,209.441,196.679,253.485,195.961,319.351,217.146,341.418,219.568,209.071,210.661,186.149,187.378,169.490,123.020,163.532,97.349
ALMERIA,22.290,9.007,39.146,10.284,42.511,13.274,70.416,19.025,90.422,28.431,153.172,32.084,189.343,39.566,206.936,41.392,142.904,34.974,71.229,26.150,38.622,12.693,33.013,10.226
ARABA/ALAVA,14.076,4.006,18.289,4.280,23.209,6.003,26.586,8.969,25.469,11.329,24.420,13.411,28.057,20.638,31.811,20.632,26.529,14.493,28.037,10.666,24.043,6.280,24.316,5.299

In [10]:
#Exporto el csv
pernoctaciones22.to_csv('pernoctaciones22.csv')

## 2021

In [11]:
ine21= leer_archivo_rango_periodo(ruta_archivo, '2021')
ine21.head()

,ï»¿Totales Territoriales,Comunidades y Ciudades AutÃ³nomas,Provincias,Viajeros y pernoctaciones,Residencia: Nivel 1,Residencia: Nivel 2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M12,4.881.952
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M11,5.391.958
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M10,8.131.666
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M09,8.256.057
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M08,10.408.035

In [12]:
ine21_viajeros, ine21_pernoctaciones = procesar_ine_data(ine21)

In [13]:
ine21_viajeros.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M12,4.881.952
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M11,5.391.958
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M10,8.131.666
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M09,8.256.057
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2021M08,10.408.035

In [14]:
ine21_pernoctaciones.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2021M12,13.220.155
1,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2021M11,14.930.647
2,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2021M10,23.935.219
3,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2021M09,25.679.512
4,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2021M08,34.460.041

### VIAJEROS

In [15]:
viajeros21 = procesar_viajeros(ine21_viajeros)
viajeros21.head()

,2021M01_Residentes en Espana,2021M01_Residentes en el Extranjero,2021M02_Residentes en Espana,2021M02_Residentes en el Extranjero,2021M03_Residentes en Espana,2021M03_Residentes en el Extranjero,2021M04_Residentes en Espana,2021M04_Residentes en el Extranjero,2021M05_Residentes en Espana,2021M05_Residentes en el Extranjero,2021M06_Residentes en Espana,2021M06_Residentes en el Extranjero,2021M07_Residentes en Espana,2021M07_Residentes en el Extranjero,2021M08_Residentes en Espana,2021M08_Residentes en el Extranjero,2021M09_Residentes en Espana,2021M09_Residentes en el Extranjero,2021M10_Residentes en Espana,2021M10_Residentes en el Extranjero,2021M11_Residentes en Espana,2021M11_Residentes en el Extranjero,2021M12_Residentes en Espana,2021M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,16.597,1.697,16.188,1.380,31.340,2.879,38.958,2.890,51.953,7.570,94.042,17.566,181.981,31.093,238.614,38.091,155.066,50.405,131.919,52.210,87.886,20.755,72.860,12.458
ALBACETE,7.883,624,9.074,791,15.592,983,15.841,949,21.033,1.689,25.515,1.781,28.908,1.904,32.897,2.407,29.538,2.961,32.249,2.984,23.843,2.735,21.998,1.812
ALICANTE,26.735,8.012,22.719,4.684,53.051,9.187,74.600,12.563,133.769,28.038,238.968,49.979,348.139,85.451,393.893,127.562,228.753,116.046,200.707,140.659,123.399,92.713,128.079,61.512
ALMERIA,10.078,2.627,10.712,1.767,14.623,2.777,16.155,3.440,37.240,5.832,107.549,10.941,172.883,16.631,209.996,20.009,133.713,26.258,67.943,21.944,32.281,10.937,30.542,9.503
ARABA/ALAVA,6.823,2.155,6.304,1.226,12.678,1.986,12.639,2.098,15.377,2.643,20.582,4.264,28.214,10.619,38.753,12.265,26.044,10.044,29.148,9.204,22.056,6.302,21.270,4.488

In [16]:
#Exporto el csv
viajeros21.to_csv('viajeros21.csv')

### PERNOCTACIONES

In [17]:
pernoctaciones21 = procesar_viajeros(ine21_pernoctaciones)
pernoctaciones21.head()

,2021M01_Residentes en Espana,2021M01_Residentes en el Extranjero,2021M02_Residentes en Espana,2021M02_Residentes en el Extranjero,2021M03_Residentes en Espana,2021M03_Residentes en el Extranjero,2021M04_Residentes en Espana,2021M04_Residentes en el Extranjero,2021M05_Residentes en Espana,2021M05_Residentes en el Extranjero,2021M06_Residentes en Espana,2021M06_Residentes en el Extranjero,2021M07_Residentes en Espana,2021M07_Residentes en el Extranjero,2021M08_Residentes en Espana,2021M08_Residentes en el Extranjero,2021M09_Residentes en Espana,2021M09_Residentes en el Extranjero,2021M10_Residentes en Espana,2021M10_Residentes en el Extranjero,2021M11_Residentes en Espana,2021M11_Residentes en el Extranjero,2021M12_Residentes en Espana,2021M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,45.653,5.595,40.665,4.888,70.103,9.096,75.244,9.881,99.685,18.374,176.101,32.456,360.406,58.287,510.744,71.344,309.445,84.700,244.700,83.545,167.841,37.108,145.928,24.545
ALBACETE,12.966,1.154,14.880,1.706,25.794,2.020,24.893,1.733,32.052,3.367,39.474,3.996,51.409,3.963,62.099,4.351,52.795,6.751,59.756,5.037,41.283,7.186,36.111,4.596
ALICANTE,49.969,26.158,41.984,12.737,94.067,20.269,132.489,28.764,254.183,75.113,631.774,141.724,1.105.137,287.062,1.372.977,476.311,737.832,461.986,596.214,573.456,286.156,385.674,282.392,231.830
ALMERIA,19.000,5.279,19.030,3.588,24.548,5.955,27.545,7.952,65.848,12.761,285.791,30.709,652.300,64.224,809.239,79.683,447.066,106.953,163.849,88.637,57.200,36.877,60.588,25.099
ARABA/ALAVA,13.164,4.097,13.510,3.112,23.829,3.828,24.402,4.398,27.823,4.632,38.602,8.047,52.436,16.957,80.368,17.830,51.177,18.492,56.836,16.468,43.306,13.178,42.688,8.886

In [18]:
#Exporto el csv
pernoctaciones21.to_csv('pernoctaciones21.csv')

## 2020

In [19]:
ine20= leer_archivo_rango_periodo(ruta_archivo, '2020')
ine20.head()

,ï»¿Totales Territoriales,Comunidades y Ciudades AutÃ³nomas,Provincias,Viajeros y pernoctaciones,Residencia: Nivel 1,Residencia: Nivel 2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M12,1.417.815
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M11,1.184.922
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M10,2.406.759
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M09,3.513.294
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M08,5.924.218

In [20]:
ine20_viajeros, ine20_pernoctaciones = procesar_ine_data(ine20)

In [21]:
ine20_viajeros.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M12,1.417.815
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M11,1.184.922
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M10,2.406.759
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M09,3.513.294
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2020M08,5.924.218

In [22]:
ine20_pernoctaciones.head()

,Totales_Territoriales,Comunidades_Ciudades_Autonomas,Provincias,Viajeros_Pernoctaciones,Residencia_Nivel_1,Residencia_Nivel_2,Periodo,Total
0,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2020M12,3.245.991
1,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2020M11,2.874.269
2,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2020M10,5.128.825
3,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2020M09,8.219.094
4,Total Nacional,NaN,NaN,Pernoctaciones,Total,NaN,2020M08,16.927.211

### VIAJEROS

In [23]:
viajeros20 = procesar_viajeros(ine20_viajeros)
viajeros20.head()

,2020M01_Residentes en Espana,2020M01_Residentes en el Extranjero,2020M02_Residentes en Espana,2020M02_Residentes en el Extranjero,2020M03_Residentes en Espana,2020M03_Residentes en el Extranjero,2020M04_Residentes en Espana,2020M04_Residentes en el Extranjero,2020M05_Residentes en Espana,2020M05_Residentes en el Extranjero,2020M06_Residentes en Espana,2020M06_Residentes en el Extranjero,2020M07_Residentes en Espana,2020M07_Residentes en el Extranjero,2020M08_Residentes en Espana,2020M08_Residentes en el Extranjero,2020M09_Residentes en Espana,2020M09_Residentes en el Extranjero,2020M10_Residentes en Espana,2020M10_Residentes en el Extranjero,2020M11_Residentes en Espana,2020M11_Residentes en el Extranjero,2020M12_Residentes en Espana,2020M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,66.694,16.962,74.172,19.758,27.983,6.964,0,0,1.989,135,18.973,1.485,93.285,11.394,137.008,17.248,71.300,9.193,49.290,7.301,19.494,2.921,19.753,2.012
ALBACETE,18.351,2.002,25.939,2.585,11.927,892,0,0,963,265,8.056,661,19.052,1.561,20.899,1.325,18.842,1.471,18.184,1.713,10.886,713,10.858,833
ALICANTE,119.686,97.449,179.749,115.921,66.270,70.694,0,0,2.021,378,28.692,3.750,172.389,44.885,263.321,55.719,127.606,26.354,100.070,24.438,44.674,11.186,53.698,12.153
ALMERIA,30.896,11.505,57.051,14.311,24.332,7.936,0,0,1.197,77,25.184,2.973,92.571,8.907,120.895,10.512,67.997,8.239,32.091,6.170,13.172,2.678,11.269,2.219
ARABA/ALAVA,18.569,5.416,20.938,4.646,8.491,2.797,0,0,826,256,6.594,1.043,16.245,5.498,20.302,6.705,15.353,2.615,15.012,3.005,6.116,1.449,6.626,1.647

In [24]:
#Exporto el csv
viajeros20.to_csv('viajeros20.csv')

### PERNOCTACIONES

In [25]:
pernoctaciones20 = procesar_viajeros(ine20_pernoctaciones)
pernoctaciones20.head()

,2020M01_Residentes en Espana,2020M01_Residentes en el Extranjero,2020M02_Residentes en Espana,2020M02_Residentes en el Extranjero,2020M03_Residentes en Espana,2020M03_Residentes en el Extranjero,2020M04_Residentes en Espana,2020M04_Residentes en el Extranjero,2020M05_Residentes en Espana,2020M05_Residentes en el Extranjero,2020M06_Residentes en Espana,2020M06_Residentes en el Extranjero,2020M07_Residentes en Espana,2020M07_Residentes en el Extranjero,2020M08_Residentes en Espana,2020M08_Residentes en el Extranjero,2020M09_Residentes en Espana,2020M09_Residentes en el Extranjero,2020M10_Residentes en Espana,2020M10_Residentes en el Extranjero,2020M11_Residentes en Espana,2020M11_Residentes en el Extranjero,2020M12_Residentes en Espana,2020M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,129.023,36.880,145.266,41.169,57.765,15.579,0,0,5.158,613,32.393,3.420,196.948,24.363,282.290,33.433,127.287,19.476,99.197,16.836,50.983,11.497,52.413,6.815
ALBACETE,27.027,4.582,40.063,6.776,20.060,2.801,0,0,1.936,1.375,14.316,2.219,33.280,4.065,41.770,2.489,31.114,2.987,30.520,3.821,18.836,1.732,17.776,1.572
ALICANTE,371.177,456.160,481.001,513.498,189.473,339.418,0,0,4.010,655,48.884,6.817,408.917,132.923,729.183,174.664,315.741,74.186,223.065,63.712,81.520,27.261,97.728,30.861
ALMERIA,67.652,39.486,132.758,59.716,80.800,31.679,0,0,2.408,130,49.630,4.843,290.200,24.448,411.380,37.708,203.000,22.945,68.053,13.357,24.161,5.962,20.158,4.931
ARABA/ALAVA,33.699,9.803,37.775,9.296,17.097,5.647,0,0,3.708,906,13.825,2.515,30.502,8.849,41.086,10.111,29.721,5.616,28.207,6.407,14.890,3.491,13.809,3.606

In [26]:
#Exporto el csv
pernoctaciones20.to_csv('pernoctaciones20.csv')

## 2019

In [27]:
ine19= leer_archivo_rango_periodo(ruta_archivo, '2019')
ine19.head()

,ï»¿Totales Territoriales,Comunidades y Ciudades AutÃ³nomas,Provincias,Viajeros y pernoctaciones,Residencia: Nivel 1,Residencia: Nivel 2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2019M12,6.240.788
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2019M11,6.693.210
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2019M10,9.772.631
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2019M09,11.038.778
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2019M08,13.028.096

In [28]:
ine19_viajeros, ine19_pernoctaciones = procesar_ine_data(ine19)

### VIAJEROS

In [29]:
viajeros19 = procesar_viajeros(ine19_viajeros)
viajeros19.head()

,2019M01_Residentes en Espana,2019M01_Residentes en el Extranjero,2019M02_Residentes en Espana,2019M02_Residentes en el Extranjero,2019M03_Residentes en Espana,2019M03_Residentes en el Extranjero,2019M04_Residentes en Espana,2019M04_Residentes en el Extranjero,2019M05_Residentes en Espana,2019M05_Residentes en el Extranjero,2019M06_Residentes en Espana,2019M06_Residentes en el Extranjero,2019M07_Residentes en Espana,2019M07_Residentes en el Extranjero,2019M08_Residentes en Espana,2019M08_Residentes en el Extranjero,2019M09_Residentes en Espana,2019M09_Residentes en el Extranjero,2019M10_Residentes en Espana,2019M10_Residentes en el Extranjero,2019M11_Residentes en Espana,2019M11_Residentes en el Extranjero,2019M12_Residentes en Espana,2019M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,61.720,14.508,69.370,14.507,79.408,25.439,101.211,59.056,110.184,91.799,115.170,85.363,156.522,66.236,195.776,75.809,127.009,96.970,107.150,80.071,81.633,26.033,79.816,16.713
ALBACETE,16.724,1.991,22.772,2.603,27.553,2.559,33.564,3.179,33.568,3.749,32.878,3.372,29.658,3.599,31.803,3.343,33.032,3.447,33.349,3.797,28.724,2.654,24.060,2.271
ALICANTE,138.245,100.324,163.790,113.873,188.843,146.402,208.067,176.826,198.944,203.063,255.803,197.779,317.906,208.572,366.796,205.907,211.311,217.481,189.099,193.405,181.122,137.583,158.795,102.588
ALMERIA,28.943,9.840,47.938,11.589,65.238,15.701,83.625,22.913,90.987,37.121,152.103,43.429,183.540,50.716,212.170,51.605,131.278,44.213,66.503,30.542,46.491,14.050,42.212,10.164
ARABA/ALAVA,16.773,4.936,18.494,4.091,24.469,6.301,25.217,9.287,24.213,11.883,25.669,11.800,25.364,17.327,30.495,19.250,26.055,13.861,26.593,10.085,24.533,6.081,24.722,4.623

In [30]:
#Exporto el csv
viajeros19.to_csv('viajeros19.csv')

### PERNOCTACIONES

In [31]:
pernoctaciones19 = procesar_viajeros(ine19_pernoctaciones)
pernoctaciones19.head()

,2019M01_Residentes en Espana,2019M01_Residentes en el Extranjero,2019M02_Residentes en Espana,2019M02_Residentes en el Extranjero,2019M03_Residentes en Espana,2019M03_Residentes en el Extranjero,2019M04_Residentes en Espana,2019M04_Residentes en el Extranjero,2019M05_Residentes en Espana,2019M05_Residentes en el Extranjero,2019M06_Residentes en Espana,2019M06_Residentes en el Extranjero,2019M07_Residentes en Espana,2019M07_Residentes en el Extranjero,2019M08_Residentes en Espana,2019M08_Residentes en el Extranjero,2019M09_Residentes en Espana,2019M09_Residentes en el Extranjero,2019M10_Residentes en Espana,2019M10_Residentes en el Extranjero,2019M11_Residentes en Espana,2019M11_Residentes en el Extranjero,2019M12_Residentes en Espana,2019M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,111.602,29.721,125.958,28.865,145.861,51.573,190.217,100.613,205.266,147.322,213.115,142.808,341.356,123.413,438.877,133.955,241.831,165.066,208.173,140.896,161.816,52.586,148.719,36.632
ALBACETE,25.173,4.726,34.947,7.661,47.206,5.361,65.563,5.370,64.229,6.176,60.869,6.050,61.289,6.711,74.836,5.883,69.709,5.965,70.309,7.568,58.627,6.605,39.361,5.107
ALICANTE,453.794,493.787,492.232,509.649,610.264,684.032,732.499,752.513,654.280,875.343,800.624,909.269,1.129.552,954.160,1.369.903,942.962,752.460,993.642,608.313,964.604,547.429,644.217,472.268,474.235
ALMERIA,67.570,40.170,121.621,52.701,235.594,65.815,301.825,84.417,255.142,166.683,435.172,237.557,719.425,244.234,823.539,268.603,456.806,250.420,147.884,150.382,100.161,51.899,95.752,32.133
ARABA/ALAVA,31.694,10.753,32.452,9.950,43.274,13.848,47.048,18.845,44.736,25.302,46.405,23.560,50.727,30.033,67.404,29.820,49.423,25.517,48.587,20.326,45.532,12.265,45.376,9.283

In [32]:
#Exporto el csv
pernoctaciones19.to_csv('pernoctaciones19.csv')

## 2018

In [33]:
ine18= leer_archivo_rango_periodo(ruta_archivo, '2018')
ine18.head()

,ï»¿Totales Territoriales,Comunidades y Ciudades AutÃ³nomas,Provincias,Viajeros y pernoctaciones,Residencia: Nivel 1,Residencia: Nivel 2,Periodo,Total
0,Total Nacional,NaN,NaN,Viajero,Total,NaN,2018M12,6.071.139
1,Total Nacional,NaN,NaN,Viajero,Total,NaN,2018M11,6.485.702
2,Total Nacional,NaN,NaN,Viajero,Total,NaN,2018M10,9.666.570
3,Total Nacional,NaN,NaN,Viajero,Total,NaN,2018M09,11.000.902
4,Total Nacional,NaN,NaN,Viajero,Total,NaN,2018M08,12.500.596

In [34]:
ine18_viajeros, ine18_pernoctaciones = procesar_ine_data(ine18)

### VIAJEROS

In [35]:
viajeros18 = procesar_viajeros(ine18_viajeros)
viajeros18.head()

,2018M01_Residentes en Espana,2018M01_Residentes en el Extranjero,2018M02_Residentes en Espana,2018M02_Residentes en el Extranjero,2018M03_Residentes en Espana,2018M03_Residentes en el Extranjero,2018M04_Residentes en Espana,2018M04_Residentes en el Extranjero,2018M05_Residentes en Espana,2018M05_Residentes en el Extranjero,2018M06_Residentes en Espana,2018M06_Residentes en el Extranjero,2018M07_Residentes en Espana,2018M07_Residentes en el Extranjero,2018M08_Residentes en Espana,2018M08_Residentes en el Extranjero,2018M09_Residentes en Espana,2018M09_Residentes en el Extranjero,2018M10_Residentes en Espana,2018M10_Residentes en el Extranjero,2018M11_Residentes en Espana,2018M11_Residentes en el Extranjero,2018M12_Residentes en Espana,2018M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,57.188,14.014,65.662,16.209,89.761,26.044,94.942,47.970,96.543,88.112,116.477,81.602,153.479,67.530,187.362,83.274,122.425,87.336,106.921,70.710,80.528,26.098,79.191,16.504
ALBACETE,15.535,2.067,19.237,2.228,27.776,2.718,29.958,2.970,28.575,2.987,30.606,2.766,27.217,2.769,30.549,2.840,33.666,3.723,33.497,3.355,25.693,2.211,23.600,1.768
ALICANTE,121.926,99.916,146.024,104.706,197.035,151.379,207.360,184.480,175.980,216.679,227.981,203.655,288.277,209.909,317.183,204.241,199.793,228.751,174.884,205.717,165.236,136.527,165.309,106.513
ALMERIA,27.864,10.077,46.952,12.173,71.626,17.147,81.800,23.033,85.566,39.624,139.785,44.055,172.091,49.047,205.644,57.449,139.448,47.759,78.403,34.288,47.744,12.389,40.198,8.725
ARABA/ALAVA,17.992,5.147,17.968,3.800,25.487,5.871,24.296,9.504,26.219,14.128,25.765,12.275,25.447,18.632,29.915,21.103,26.667,13.686,27.331,11.095,24.242,5.670,23.938,4.388

In [36]:
#Exporto el csv
viajeros18.to_csv('viajeros18.csv')

### PERNOCTACIONES

In [37]:
pernoctaciones18 = procesar_viajeros(ine18_pernoctaciones)
pernoctaciones18.head()

,2018M01_Residentes en Espana,2018M01_Residentes en el Extranjero,2018M02_Residentes en Espana,2018M02_Residentes en el Extranjero,2018M03_Residentes en Espana,2018M03_Residentes en el Extranjero,2018M04_Residentes en Espana,2018M04_Residentes en el Extranjero,2018M05_Residentes en Espana,2018M05_Residentes en el Extranjero,2018M06_Residentes en Espana,2018M06_Residentes en el Extranjero,2018M07_Residentes en Espana,2018M07_Residentes en el Extranjero,2018M08_Residentes en Espana,2018M08_Residentes en el Extranjero,2018M09_Residentes en Espana,2018M09_Residentes en el Extranjero,2018M10_Residentes en Espana,2018M10_Residentes en el Extranjero,2018M11_Residentes en Espana,2018M11_Residentes en el Extranjero,2018M12_Residentes en Espana,2018M12_Residentes en el Extranjero
Provincias,,,,,,,,,,,,,,,,,,,,,,,,
A CORUÑA,101.197,29.889,117.828,32.514,159.821,45.396,168.387,86.374,170.188,141.556,197.600,132.645,331.941,121.399,409.023,144.713,232.065,144.598,198.879,115.452,159.435,65.839,145.967,31.601
ALBACETE,22.166,3.710,28.928,4.769,49.833,5.048,58.963,5.295,58.268,4.951,57.401,4.598,57.120,4.833,70.509,5.542,68.118,7.220,69.941,5.855,53.065,4.364,38.542,3.433
ALICANTE,412.427,490.321,429.796,498.378,640.818,693.579,681.438,823.538,571.945,1.012.433,741.725,987.699,1.036.052,1.029.974,1.239.986,1.012.504,710.347,1.102.716,613.612,1.029.503,530.713,673.322,521.622,495.975
ALMERIA,69.310,38.414,118.696,58.364,266.817,70.098,296.926,84.429,265.718,177.521,413.874,256.929,698.663,268.014,785.951,287.817,467.722,271.167,200.189,187.269,111.217,49.367,94.660,31.297
ARABA/ALAVA,32.173,9.788,32.185,7.004,45.874,11.395,45.407,16.722,45.483,25.255,45.960,23.516,51.004,30.682,69.347,33.147,52.959,24.929,52.131,22.238,46.069,12.907,45.816,9.670

# Juntar DF

In [38]:
# Concatenar los DataFrames a lo largo de las columnas
viajeros_combined = pd.concat([viajeros18, viajeros19, viajeros20, viajeros21, viajeros22], axis=1)

In [39]:
viajeros_combined.reset_index(inplace=True)

# Mover 'Provincias' a una nueva columna
viajeros_combined['Provincias'] = viajeros_combined['Provincias']

# Crear un nuevo índice 'id_viajeros_combinated'
viajeros_combined['id_viajeros_combined'] = range(1, len(viajeros_combined) + 1)

# Establecer 'id_viajeros_combinated' como el nuevo índice
viajeros_combined.set_index('id_viajeros_combined', inplace=True)

# Imprimir el DataFrame resultante
viajeros_combined.head()

,Provincias,2018M01_Residentes en Espana,2018M01_Residentes en el Extranjero,2018M02_Residentes en Espana,2018M02_Residentes en el Extranjero,2018M03_Residentes en Espana,2018M03_Residentes en el Extranjero,2018M04_Residentes en Espana,2018M04_Residentes en el Extranjero,2018M05_Residentes en Espana,2018M05_Residentes en el Extranjero,2018M06_Residentes en Espana,2018M06_Residentes en el Extranjero,2018M07_Residentes en Espana,2018M07_Residentes en el Extranjero,2018M08_Residentes en Espana,2018M08_Residentes en el Extranjero,2018M09_Residentes en Espana,2018M09_Residentes en el Extranjero,2018M10_Residentes en Espana,2018M10_Residentes en el Extranjero,2018M11_Residentes en Espana,2018M11_Residentes en el Extranjero,2018M12_Residentes en Espana,2018M12_Residentes en el Extranjero,2019M01_Residentes en Espana,2019M01_Residentes en el Extranjero,2019M02_Residentes en Espana,2019M02_Residentes en el Extranjero,2019M03_Residentes en Espana,2019M03_Residentes en el Extranjero,2019M04_Residentes en Espana,2019M04_Residentes en el Extranjero,2019M05_Residentes en Espana,2019M05_Residentes en el Extranjero,2019M06_Residentes en Espana,2019M06_Residentes en el Extranjero,2019M07_Residentes en Espana,2019M07_Residentes en el Extranjero,2019M08_Residentes en Espana,2019M08_Residentes en el Extranjero,2019M09_Residentes en Espana,2019M09_Residentes en el Extranjero,2019M10_Residentes en Espana,2019M10_Residentes en el Extranjero,2019M11_Residentes en Espana,2019M11_Residentes en el Extranjero,2019M12_Residentes en Espana,2019M12_Residentes en el Extranjero,2020M01_Residentes en Espana,2020M01_Residentes en el Extranjero,2020M02_Residentes en Espana,2020M02_Residentes en el Extranjero,2020M03_Residentes en Espana,2020M03_Residentes en el Extranjero,2020M04_Residentes en Espana,2020M04_Residentes en el Extranjero,2020M05_Residentes en Espana,2020M05_Residentes en el Extranjero,2020M06_Residentes en Espana,2020M06_Residentes en el Extranjero,2020M07_Residentes en Espana,2020M07_Residentes en el Extranjero,2020M08_Residentes en Espana,2020M08_Residentes en el Extranjero,2020M09_Residentes en Espana,2020M09_Residentes en el Extranjero,2020M10_Residentes en Espana,2020M10_Residentes en el Extranjero,2020M11_Residentes en Espana,2020M11_Residentes en el Extranjero,2020M12_Residentes en Espana,2020M12_Residentes en el Extranjero,2021M01_Residentes en Espana,2021M01_Residentes en el Extranjero,2021M02_Residentes en Espana,2021M02_Residentes en el Extranjero,2021M03_Residentes en Espana,2021M03_Residentes en el Extranjero,2021M04_Residentes en Espana,2021M04_Residentes en el Extranjero,2021M05_Residentes en Espana,2021M05_Residentes en el Extranjero,2021M06_Residentes en Espana,2021M06_Residentes en el Extranjero,2021M07_Residentes en Espana,2021M07_Residentes en el Extranjero,2021M08_Residentes en Espana,2021M08_Residentes en el Extranjero,2021M09_Residentes en Espana,2021M09_Residentes en el Extranjero,2021M10_Residentes en Espana,2021M10_Residentes en el Extranjero,2021M11_Residentes en Espana,2021M11_Residentes en el Extranjero,2021M12_Residentes en Espana,2021M12_Residentes en el Extranjero,2022M01_Residentes en Espana,2022M01_Residentes en el Extranjero,2022M02_Residentes en Espana,2022M02_Residentes en el Extranjero,2022M03_Residentes en Espana,2022M03_Residentes en el Extranjero,2022M04_Residentes en Espana,2022M04_Residentes en el Extranjero,2022M05_Residentes en Espana,2022M05_Residentes en el Extranjero,2022M06_Residentes en Espana,2022M06_Residentes en el Extranjero,2022M07_Residentes en Espana,2022M07_Residentes en el Extranjero,2022M08_Residentes en Espana,2022M08_Residentes en el Extranjero,2022M09_Residentes en Espana,2022M09_Residentes en el Extranjero,2022M10_Residentes en Espana,2022M10_Residentes en el Extranjero,2022M11_Residentes en Espana,2022M11_Residentes en el Extranjero,2022M12_Residentes en Espana,2022M12_Residentes en el Extranjero
id_viajeros_combined,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,A CORUÑA,57.188,14.014,65.662,16.209,89.761,26.044,94.942,47.970,96.543,88.112,116.477,81.602,153.479,67.530,187.362,83.274,122.425,87.336,106.921,70.710,80.528,26.098,79.191,16.504,61.720,14.508,69.370,14.507,79.408,25.439,101.211,59.056,110.184,91.799,115.170,85.363,156.522,66.236,195.776,75.809,127.009,96.970,107.150,80.071,81.633,26.033,79.816,16.713,66.694,16.962,74.172,19.758,27.983,6.964,0,0,1.989,135,18.973,1.485,93.285,11.394,137.008,17.248,71.300,9.193,49.290,7.301,19.494,2.921,19.753,2.012,16.597,1.697,16.188,1.380,31.340,2.879,38.958,2.890,51.953,7.570,94.042,17.566,181.981,31.093,238.614,38.091,155.066,50.405,131.919,52.210,87.886,20.755,72.860,12.458,51.283,10.804,72.223,13.320,82.649,24.794,119.875,57.536,119.893,97.410,132.289,94.573,194.874,82.142,232.843,80.681,150.900,105.761,131.666,94.199,94.029,28.034,79.982,18.050
2,ALBACETE,15.535,2.067,19.237,2.228,27.776,2.718,29.958,2.970,28.575,2.987,30.606,2.766,27.217,2.769,30.549,2.840,33.666,3.723,33.497,3.355,25.693,2.211,23.600,1.768,16.724,1.991,22.772,2.603,27.553,2.559,33.564,3.179,33.568,3.749,32.878,3.372,29.658,3.599,31.803,3.343,33.032,3.447,33.349,3.797,28.724,2.654,24.060,2.271,18.351,2.002,25.939,2.585,11.927,892,0,0,963,265,8.056,661,19.052,1.561,20.899,1.325,18.842,1.471,18.184,1.713,10.886,713,10.858,833,7.883,624,9.074,791,15.592,983,15.841,949,21.033,1.689,25.515,1.781,28.908,1.904,32.897,2.407,29.538,2.961,32.249,2.984,23.843,2.735,21.998,1.812,15.963,1.525,20.754,2.755,25.686,2.440,33.808,3.040,31.837,3.871,31.137,3.350,29.234,3.624,33.219,4.218,34.265,3.715,32.825,3.847,26.850,3.848,23.932,2.356
3,ALICANTE,121.926,99.916,146.024,104.706,197.035,151.379,207.360,184.480,175.980,216.679,227.981,203.655,288.277,209.909,317.183,204.241,199.793,228.751,174.884,205.717,165.236,136.527,165.309,106.513,138.245,100.324,163.790,113.873,188.843,146.402,208.067,176.826,198.944,203.063,255.803,197.779,317.906,208.572,366.796,205.907,211.311,217.481,189.099,193.405,181.122,137.583,158.795,102.588,119.686,97.449,179.749,115.921,66.270,70.694,0,0,2.021,378,28.692,3.750,172.389,44.885,263.321,55.719,127.606,26.354,100.070,24.438,44.674,11.186,53.698,12.153,26.735,8.012,22.719,4.684,53.051,9.187,74.600,12.563,133.769,28.038,238.968,49.979,348.139,85.451,393.893,127.562,228.753,116.046,200.707,140.659,123.399,92.713,128.079,61.512,75.778,49.765,133.494,78.422,135.526,124.360,221.231,168.677,209.441,196.679,253.485,195.961,319.351,217.146,341.418,219.568,209.071,210.661,186.149,187.378,169.490,123.020,163.532,97.349
4,ALMERIA,27.864,10.077,46.952,12.173,71.626,17.147,81.800,23.033,85.566,39.624,139.785,44.055,172.091,49.047,205.644,57.449,139.448,47.759,78.403,34.288,47.744,12.389,40.198,8.725,28.943,9.840,47.938,11.589,65.238,15.701,83.625,22.913,90.987,37.121,152.103,43.429,183.540,50.716,212.170,51.605,131.278,44.213,66.503,30.542,46.491,14.050,42.212,10.164,30.896,11.505,57.051,14.311,24.332,7.936,0,0,1.197,77,25.184,2.973,92.571,8.907,120.895,10.512,67.997,8.239,32.091,6.170,13.172,2.678,11.269,2.219,10.078,2.627,10.712,1.767,14.623,2.777,16.155,3.440,37.240,5.832,107.549,10.941,172.883,16.631,209.996,20.009,133.713,26.258,67.943,21.944,32.281,10.937,30.542,9.503,22.290,9.007,39.146,10.284,42.511,13.274,70.416,19.025,90.422,28.431,153.172,32.084,189.343,39.566,206.936,41.392,142.904,34.974,71.229,26.150,38.622,12.693,33.013,10.226
5,ARABA/ALAVA,17.992,5.147,17.968,3.800,25.487,5.871,24.296,9.504,26.219,14.128,25.765,12.275,25.447,18.632,29.915,21.103,26.667,13.686,27.331,11.095,24.242,5.670,23.938,4.388,16.773,4.936,18.494,4.091,24.469,6.301,25.217,9.287,24.213,11.883,25.669,11.800,25.364,17.327,30.495,19.250,26.055,13.861,26.593,10.085,24.533,6.081,24.722,4.623,18.569,5.416,20.938,4.646,8.491,2.797,0,0,826,256,6.594,1.043,16.245,5.498,20.302,6.705,15.353,2.615,15.012,3.005,6.116,1.449,6.626,1.647,6.823,2.155,6.304,1.226,12.678,1.986,12.639,2.098,15.377,2.643,20.582,4.264,28.214,10.619,38.753,12.265,26.044,10.044,29.148,9.204,22.056,6.302,21.270,4.488,14.076,4.006,18.289,4.280,23.209,6.003,26.586,8.969,25.469,11.329,24.420,13.411,28.057,20.638,31.811,20.632,26.529,14.493,28.037,10.666,24.043,6.280,24.316,5.299

In [40]:
# Mostrar información sobre el nuevo DataFrame
print(viajeros_combined.info())

# Guardar el DataFrame combinado en un nuevo archivo si es necesario
viajeros_combined.to_csv('viajeros_combined.csv')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1 to 50
Columns: 121 entries, Provincias to 2022M12_Residentes en el Extranjero
dtypes: object(121)
memory usage: 47.7+ KB
None

In [41]:
# Concatenar los DataFrames a lo largo de las columnas
pernoctaciones_combined = pd.concat([pernoctaciones18, pernoctaciones19, pernoctaciones20, pernoctaciones21, pernoctaciones22], axis=1)

In [44]:
pernoctaciones_combined.reset_index(inplace=True)

# Muevo 'Provincias' a una nueva columna
pernoctaciones_combined['Provincias'] = pernoctaciones_combined['Provincias']

# Creoun nuevo índice 'id_viajeros_combinated'
pernoctaciones_combined['id_pernoctaciones_combined'] = range(1, len(pernoctaciones_combined) + 1)

# Establezco'id_viajeros_combinated' como el nuevo índice
pernoctaciones_combined.set_index('id_pernoctaciones_combined', inplace=True)

# Imprimir el DataFrame resultante
pernoctaciones_combined.head()

,Provincias,2018M01_Residentes en Espana,2018M01_Residentes en el Extranjero,2018M02_Residentes en Espana,2018M02_Residentes en el Extranjero,2018M03_Residentes en Espana,2018M03_Residentes en el Extranjero,2018M04_Residentes en Espana,2018M04_Residentes en el Extranjero,2018M05_Residentes en Espana,2018M05_Residentes en el Extranjero,2018M06_Residentes en Espana,2018M06_Residentes en el Extranjero,2018M07_Residentes en Espana,2018M07_Residentes en el Extranjero,2018M08_Residentes en Espana,2018M08_Residentes en el Extranjero,2018M09_Residentes en Espana,2018M09_Residentes en el Extranjero,2018M10_Residentes en Espana,2018M10_Residentes en el Extranjero,2018M11_Residentes en Espana,2018M11_Residentes en el Extranjero,2018M12_Residentes en Espana,2018M12_Residentes en el Extranjero,2019M01_Residentes en Espana,2019M01_Residentes en el Extranjero,2019M02_Residentes en Espana,2019M02_Residentes en el Extranjero,2019M03_Residentes en Espana,2019M03_Residentes en el Extranjero,2019M04_Residentes en Espana,2019M04_Residentes en el Extranjero,2019M05_Residentes en Espana,2019M05_Residentes en el Extranjero,2019M06_Residentes en Espana,2019M06_Residentes en el Extranjero,2019M07_Residentes en Espana,2019M07_Residentes en el Extranjero,2019M08_Residentes en Espana,2019M08_Residentes en el Extranjero,2019M09_Residentes en Espana,2019M09_Residentes en el Extranjero,2019M10_Residentes en Espana,2019M10_Residentes en el Extranjero,2019M11_Residentes en Espana,2019M11_Residentes en el Extranjero,2019M12_Residentes en Espana,2019M12_Residentes en el Extranjero,2020M01_Residentes en Espana,2020M01_Residentes en el Extranjero,2020M02_Residentes en Espana,2020M02_Residentes en el Extranjero,2020M03_Residentes en Espana,2020M03_Residentes en el Extranjero,2020M04_Residentes en Espana,2020M04_Residentes en el Extranjero,2020M05_Residentes en Espana,2020M05_Residentes en el Extranjero,2020M06_Residentes en Espana,2020M06_Residentes en el Extranjero,2020M07_Residentes en Espana,2020M07_Residentes en el Extranjero,2020M08_Residentes en Espana,2020M08_Residentes en el Extranjero,2020M09_Residentes en Espana,2020M09_Residentes en el Extranjero,2020M10_Residentes en Espana,2020M10_Residentes en el Extranjero,2020M11_Residentes en Espana,2020M11_Residentes en el Extranjero,2020M12_Residentes en Espana,2020M12_Residentes en el Extranjero,2021M01_Residentes en Espana,2021M01_Residentes en el Extranjero,2021M02_Residentes en Espana,2021M02_Residentes en el Extranjero,2021M03_Residentes en Espana,2021M03_Residentes en el Extranjero,2021M04_Residentes en Espana,2021M04_Residentes en el Extranjero,2021M05_Residentes en Espana,2021M05_Residentes en el Extranjero,2021M06_Residentes en Espana,2021M06_Residentes en el Extranjero,2021M07_Residentes en Espana,2021M07_Residentes en el Extranjero,2021M08_Residentes en Espana,2021M08_Residentes en el Extranjero,2021M09_Residentes en Espana,2021M09_Residentes en el Extranjero,2021M10_Residentes en Espana,2021M10_Residentes en el Extranjero,2021M11_Residentes en Espana,2021M11_Residentes en el Extranjero,2021M12_Residentes en Espana,2021M12_Residentes en el Extranjero,2022M01_Residentes en Espana,2022M01_Residentes en el Extranjero,2022M02_Residentes en Espana,2022M02_Residentes en el Extranjero,2022M03_Residentes en Espana,2022M03_Residentes en el Extranjero,2022M04_Residentes en Espana,2022M04_Residentes en el Extranjero,2022M05_Residentes en Espana,2022M05_Residentes en el Extranjero,2022M06_Residentes en Espana,2022M06_Residentes en el Extranjero,2022M07_Residentes en Espana,2022M07_Residentes en el Extranjero,2022M08_Residentes en Espana,2022M08_Residentes en el Extranjero,2022M09_Residentes en Espana,2022M09_Residentes en el Extranjero,2022M10_Residentes en Espana,2022M10_Residentes en el Extranjero,2022M11_Residentes en Espana,2022M11_Residentes en el Extranjero,2022M12_Residentes en Espana,2022M12_Residentes en el Extranjero
id_pernoctaciones_combined,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,A CORUÑA,101.197,29.889,117.828,32.514,159.821,45.396,168.387,86.374,170.188,141.556,197.600,132.645,331.941,121.399,409.023,144.713,232.065,144.598,198.879,115.452,159.435,65.839,145.967,31.601,111.602,29.721,125.958,28.865,145.861,51.573,190.217,100.613,205.266,147.322,213.115,142.808,341.356,123.413,438.877,133.955,241.831,165.066,208.173,140.896,161.816,52.586,148.719,36.632,129.023,36.880,145.266,41.169,57.765,15.579,0,0,5.158,613,32.393,3.420,196.948,24.363,282.290,33.433,127.287,19.476,99.197,16.836,50.983,11.497,52.413,6.815,45.653,5.595,40.665,4.888,70.103,9.096,75.244,9.881,99.685,18.374,176.101,32.456,360.406,58.287,510.744,71.344,309.445,84.700,244.700,83.545,167.841,37.108,145.928,24.545,51.283,10.804,72.223,13.320,82.649,24.794,119.875,57.536,119.893,97.410,132.289,94.573,194.874,82.142,232.843,80.681,150.900,105.761,131.666,94.199,94.029,28.034,79.982,18.050
2,ALBACETE,22.166,3.710,28.928,4.769,49.833,5.048,58.963,5.295,58.268,4.951,57.401,4.598,57.120,4.833,70.509,5.542,68.118,7.220,69.941,5.855,53.065,4.364,38.542,3.433,25.173,4.726,34.947,7.661,47.206,5.361,65.563,5.370,64.229,6.176,60.869,6.050,61.289,6.711,74.836,5.883,69.709,5.965,70.309,7.568,58.627,6.605,39.361,5.107,27.027,4.582,40.063,6.776,20.060,2.801,0,0,1.936,1.375,14.316,2.219,33.280,4.065,41.770,2.489,31.114,2.987,30.520,3.821,18.836,1.732,17.776,1.572,12.966,1.154,14.880,1.706,25.794,2.020,24.893,1.733,32.052,3.367,39.474,3.996,51.409,3.963,62.099,4.351,52.795,6.751,59.756,5.037,41.283,7.186,36.111,4.596,15.963,1.525,20.754,2.755,25.686,2.440,33.808,3.040,31.837,3.871,31.137,3.350,29.234,3.624,33.219,4.218,34.265,3.715,32.825,3.847,26.850,3.848,23.932,2.356
3,ALICANTE,412.427,490.321,429.796,498.378,640.818,693.579,681.438,823.538,571.945,1.012.433,741.725,987.699,1.036.052,1.029.974,1.239.986,1.012.504,710.347,1.102.716,613.612,1.029.503,530.713,673.322,521.622,495.975,453.794,493.787,492.232,509.649,610.264,684.032,732.499,752.513,654.280,875.343,800.624,909.269,1.129.552,954.160,1.369.903,942.962,752.460,993.642,608.313,964.604,547.429,644.217,472.268,474.235,371.177,456.160,481.001,513.498,189.473,339.418,0,0,4.010,655,48.884,6.817,408.917,132.923,729.183,174.664,315.741,74.186,223.065,63.712,81.520,27.261,97.728,30.861,49.969,26.158,41.984,12.737,94.067,20.269,132.489,28.764,254.183,75.113,631.774,141.724,1.105.137,287.062,1.372.977,476.311,737.832,461.986,596.214,573.456,286.156,385.674,282.392,231.830,75.778,49.765,133.494,78.422,135.526,124.360,221.231,168.677,209.441,196.679,253.485,195.961,319.351,217.146,341.418,219.568,209.071,210.661,186.149,187.378,169.490,123.020,163.532,97.349
4,ALMERIA,69.310,38.414,118.696,58.364,266.817,70.098,296.926,84.429,265.718,177.521,413.874,256.929,698.663,268.014,785.951,287.817,467.722,271.167,200.189,187.269,111.217,49.367,94.660,31.297,67.570,40.170,121.621,52.701,235.594,65.815,301.825,84.417,255.142,166.683,435.172,237.557,719.425,244.234,823.539,268.603,456.806,250.420,147.884,150.382,100.161,51.899,95.752,32.133,67.652,39.486,132.758,59.716,80.800,31.679,0,0,2.408,130,49.630,4.843,290.200,24.448,411.380,37.708,203.000,22.945,68.053,13.357,24.161,5.962,20.158,4.931,19.000,5.279,19.030,3.588,24.548,5.955,27.545,7.952,65.848,12.761,285.791,30.709,652.300,64.224,809.239,79.683,447.066,106.953,163.849,88.637,57.200,36.877,60.588,25.099,22.290,9.007,39.146,10.284,42.511,13.274,70.416,19.025,90.422,28.431,153.172,32.084,189.343,39.566,206.936,41.392,142.904,34.974,71.229,26.150,38.622,12.693,33.013,10.226
5,ARABA/ALAVA,32.173,9.788,32.185,7.004,45.874,11.395,45.407,16.722,45.483,25.255,45.960,23.516,51.004,30.682,69.347,33.147,52.959,24.929,52.131,22.238,46.069,12.907,45.816,9.670,31.694,10.753,32.452,9.950,43.274,13.848,47.048,18.845,44.736,25.302,46.405,23.560,50.727,30.033,67.404,29.820,49.423,25.517,48.587,20.326,45.532,12.265,45.376,9.283,33.699,9.803,37.775,9.296,17.097,5.647,0,0,3.708,906,13.825,2.515,30.502,8.849,41.086,10.111,29.721,5.616,28.207,6.407,14.890,3.491,13.809,3.606,13.164,4.097,13.510,3.112,23.829,3.828,24.402,4.398,27.823,4.632,38.602,8.047,52.436,16.957,80.368,17.830,51.177,18.492,56.836,16.468,43.306,13.178,42.688,8.886,14.076,4.006,18.289,4.280,23.209,6.003,26.586,8.969,25.469,11.329,24.420,13.411,28.057,20.638,31.811,20.632,26.529,14.493,28.037,10.666,24.043,6.280,24.316,5.299

In [43]:
print(pernoctaciones_combined.info())

# Guardo el DataFrame combinado en un nuevo archivo si es necesario
pernoctaciones_combined.to_csv('pernoctaciones_combined.csv')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1 to 50
Columns: 121 entries, Provincias to 2022M12_Residentes en el Extranjero
dtypes: object(121)
memory usage: 47.7+ KB
None